meta_product_name: "Clean Up"
meta_title: "Clean Up - Trouvez un agent d'entretien en 3 clics"
meta_description: "Clean Up t'aide à trouver un agent d'entretien près de chez toi"
meta_image: "Logo_rectangle-og.png" # should exist in `app/assets/images/`
